/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ceres.gui;

import br.com.ceres.bean.Categoria;
import br.com.ceres.bean.Pedido;
import br.com.ceres.bean.Produto;
import br.com.ceres.dao.CategoriaDAO;
import br.com.ceres.dao.ProdutoDAO;
import br.com.ceres.gui.ProdutoListar;
import br.com.ceres.sessao.Sessao;
import br.com.ceres.util.Validador;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author joabe_000
 */
public class PedidoEditar extends javax.swing.JFrame {

    JDesktopPane jDesktopPane;
    Pedido pedido;
    /**
     * Creates new form ProdutoCadastrar
     * @param jDesktopPane
     * @param pedido
     */
    public PedidoEditar(JDesktopPane jDesktopPane, Pedido pedido) {
        initComponents();
        
        this.jDesktopPane = jDesktopPane;
        this.pedido = pedido;
        this.populate();
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Produto");
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populate(){
        //jTextField1.setText(pedido.getCodigo());
      //  jTextFieldNome.setText(pedido.getNome());
       // jTextAreaDescricao.setText(pedido.getDescricao());
       // jTextFieldPreco.setText(String.valueOf(pedido.getPreco()));
   }
    
    public void atualizaJDesktopPane(){
        ProdutoListar produtoListar = new ProdutoListar(jDesktopPane);
        produtoListar.setVisible(true);
        jDesktopPane.removeAll();
        jDesktopPane.add(produtoListar);
    }
    
    public void atualiza(){
        //pedido.setNome(jTextFieldNome.getText());
        //pedido.setDescricao(jTextAreaDescricao.getText());
        //pedido.setPreco(Float.parseFloat(jTextFieldPreco.getText()));
        //pedido.setCategoria((Categoria) jComboBoxCategoria.getSelectedItem());
        //pedido.setFuncionario(Sessao.getInstance().getFuncionario());

        //ProdutoDAO produtoDAO = new ProdutoDAO();
        //produtoDAO.atualizar(pedido);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
