/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ceres.gui;

import br.com.ceres.bean.Pedido;
import br.com.ceres.bean.PedidoHasProduto;
import br.com.ceres.bean.PedidoHasProdutoPK;
import br.com.ceres.bean.Produto;
import br.com.ceres.dao.PedidoHasProdutoDAO;
import br.com.ceres.dao.ProdutoDAO;
import java.util.Collection;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joabe_000
 */
public class QuantidadeProdutoPedido extends javax.swing.JFrame {

    Produto produto;
    Pedido pedido;
    JTable tabelaProdutosPedido;
    JLabel jLabelValortotal;
    /**
     * Creates new form QuantidadeProdutoPedido
     * @param produto
     * @param pedido
     * @param jTable
     * @param jLabelValortotal
     */
    public QuantidadeProdutoPedido(Produto produto, Pedido pedido, JTable jTable, JLabel jLabelValortotal) {
        initComponents();
        this.pedido = pedido;
        this.produto = produto;
        this.tabelaProdutosPedido = jTable;
        this.jLabelValortotal = jLabelValortotal;
        
        jLabelNome.setText(produto.getNome());
        jSpinnerQuantidade.setValue(1);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); 

        Object[] linha = new Object[5];
        linha[0] = produto.getId();
        linha[1] = produto.getCodigo();
        linha[2] = produto.getCategoria();
        linha[3] = produto.getNome();
        linha[4] = produto.getPreco();
        model.addRow(linha);  
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAdicionar = new javax.swing.JButton();
        jSpinnerQuantidade = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar produto ao pedido");
        setAlwaysOnTop(true);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNome.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("Quantidade");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. do sistema", "Cód. de busca", "Categoria", "Produto", "Preço"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed

        Collection<PedidoHasProduto> produtosDoPedido = this.pedido.getPedidoHasProdutoCollection();

        PedidoHasProdutoPK pedidoHasProdutoPK = new PedidoHasProdutoPK(pedido.getId(), produto.getId());
        int quantidade = (int) jSpinnerQuantidade.getValue();

        PedidoHasProduto pedidoHasProduto = new PedidoHasProduto(pedidoHasProdutoPK, quantidade, "");
        pedidoHasProduto.setPedido(pedido);
        pedidoHasProduto.setProduto(produto);
        pedidoHasProduto.setQuantidade(quantidade);

        produtosDoPedido.add(pedidoHasProduto);
        pedido.setPedidoHasProdutoCollection(produtosDoPedido);
        pedido.setValorTotalProdutos(pedidoHasProduto.getSubTotal() + pedido.getValorTotalDosProdutos());
        
        PedidoHasProdutoDAO pedidoHasProdutoDAO = new PedidoHasProdutoDAO();
        pedidoHasProdutoDAO.inserir(pedidoHasProduto);

        DefaultTableModel model = (DefaultTableModel) this.tabelaProdutosPedido.getModel(); 
        
        Object[] linha = new Object[5];
        linha[0] = pedidoHasProduto.getQuantidade();
        linha[1] = pedidoHasProduto.getProduto().getNome();
        linha[2] = pedidoHasProduto.getProduto().getPreco();
        linha[3] = pedidoHasProduto.getSubTotal();
        linha[4] = pedidoHasProduto.getProduto().getCodigo();
        model.addRow(linha);  
     
        
        this.tabelaProdutosPedido.setModel(model);
        this.tabelaProdutosPedido.repaint();

        this.jLabelValortotal.setText(String.valueOf(pedido.getValorTotalDosProdutos() + pedido.getValorEntrega()));
        //Fecha jframe
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuantidadeProdutoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuantidadeProdutoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuantidadeProdutoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuantidadeProdutoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerQuantidade;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
